const menuList = [
    {
        title:'首页',
        key:'/home',
        icon:'home',
        children:[
            {
                title:'产品介绍',
                key:'/home',
            },
            {
                title:'五星团队',
                key:'/team',
            },
            {
                title:'美味秘诀',
                key:'/secret',
            },
            {
                title:'关于我们',
                key:'/about',
            },
        ]
    },
    {
        title:'商品',
        icon:'shop',
        key:'/shop'
    },
    {
        title:'用户管理',
        icon:'user',
        key:'/user'
    },
    {
        title:'图形图表',
        icon:'charts',
        key:'/charts'
    }
]
export default menuList
